# knowledge_react_abc.py — A/B/C Test Scripts
# Krishna Furniture Reactivation Campaign
# campaign_type: react_a | react_b | react_c

REACT_A_SCRIPT = {
    "ra_greet_main": "Aap apne ghar ka furniture upgrade karna chahte ho toh ab woh bahut aasaan ho gaya hai. Hum aapka purana furniture bhi achhi value mein lete hain aur naye furniture par bhi special discount chal raha hai. 30 second mein offer samjha doon?",
    "ra_greet_who": "Jee, main Priya bol rahi hoon Krishna Furniture ki taraf se. Aap hamare customer reh chuke hain isliye maine personally phone kiya aapko. Ek khaas offer hai sirf aapke liye.",
    "ra_greet_repeat": "Haan ji — hum aapka purana furniture achhe rate mein khareed lenge aur naye par heavy discount denge. Matlab ghar ka poora look badal jaata hai aadhe daam mein.",
    "ra_greet_privacy": "Jee bilkul — aapka number hamare purane customer records mein hai. Koi third party nahi hai. Aap hamare valued customer hain isliye personally call ki.",
    "ra_greet_hostile": "Maafi chahti hoon disturb karne ke liye. WhatsApp par details bhej deti hoon — dekhna na dekhna aap par hai. Aapka din achha rahe!",
    "ra_offer_main": "Krishna Furniture mein abhi naye furniture par 25% discount chal raha hai. Aur agar aap apna purana furniture exchange karte hain toh uski value ka bhi extra benefit milta hai. Matlab overall kharcha kaafi kam ho jaata hai. Ek aur achhi baat bataun?",
    "ra_offer_explain": "Bilkul simple hai — aap showroom aao, hum aapke purane furniture ki value calculate karenge aapke saamne. Us value par 25% aur, plus upar se 25% — total saving 43 se 50%. Koi hidden condition nahi hai.",
    "ra_offer_trust": "Samajh sakti hoon — aajkal bahut calls aati hain. Aap showroom mein aa kar personally verify kar sakte hain — koi commitment nahi. Sector 14 Gurgaon, Delhi, Noida — teeno jagah hain hamare showrooms.",
    "ra_offer_urgency": "Yeh offer sirf is mahine tak hai aur pieces limited hain. Jo pehle aaya usne le liya. WhatsApp par details check karo pehle — phir decide karo.",
    "ra_obj_not_interested": "Ek baar WhatsApp par dekh lena — sirf photos aur price list. Koi pressure nahi hai. Offer is mahine tak valid hai.",
    "ra_obj_busy": "Bilkul, disturb nahi karti. Details WhatsApp par hain — apni fursad mein dekh lena.",
    "ra_obj_expensive": "Isliye toh yeh exchange offer hai — new price par nahi, exchange ke saath. Exact amount WhatsApp par dekh sakte ho.",
    "ra_obj_online": "Online mein delivery, installation, after-sales sab alag hote hain. Hamare paas factory price hai plus exchange value — total comparison WhatsApp par hai.",
    "ra_obj_think": "Zaroor socho — but offer is mahine tak hi hai. WhatsApp par details reh jaaye, jab decide karo tab kaam aayegi.",
    "ra_obj_recovery": "Sach bolunga — jo families yeh offer leke gayi hain wo bahut khush hain. Aadhe daam mein ghar ka poora look badal jaata hai. Aap bhi iska fayda uthao.",
    "ra_hook_cta": "Aap hamare purane customer hain, isliye maine personally call kiya. Mere hisaab se ek baar free furniture valuation toh kara hi lena chahiye. Uske baad decision poori tarah aapka rahega.",
    "ra_close": "Bilkul sahi decision hai. WhatsApp dekho, ek baar showroom aao — purana furniture hum sambhal lenge, aap bas naya chunna. Bahut shukriya!",
    "ra_close_conviction": "Ab der mat karo — pieces limited hain. Showroom mein aao, apne saamne value calculate karwao, aur wohi din naya furniture le jaao. Purana hum le lenge. Bahut shukriya!",
    "ra_dnc": "Maafi chahti hoon! Aapka number DNC list mein add kar diya jaayega — ab koi call nahi aayegi. Bahut bahut shukriya.",
    "ra_q_location": "Hamare showrooms Sector 14 Gurgaon, Delhi, aur Noida mein hain — Monday se Sunday, subah 10 baje se raat 8 baje tak khule rehte hain.",
    "ra_q_name": "Mera naam Priya hai — main Krishna Furniture ki taraf se baat kar rahi hoon.",
    "ra_q_valuation": "Bahut simple hai — hamari team aapke ghar aakar purana furniture dekh kar uski value batayegi, wahi se pickup bhi ho jaayega. Aapke saamne hi sab hoga.",
    "ra_appointment_ask": "Main aapke liye free valuation visit book kar deti hoon. Hamari team aa kar furniture dekh legi, value bata degi, uske baad hi aap decide kariyega. Kaunsi date convenient rahegi?",
    "ra_appointment_confirmed": "Bahut badiya ji. Main appointment confirm kar deti hoon. Hamari team time par pahunch jayegi. Jaldi milte hain!",
    "ra_appointment_reask": "Maaf kijiye, samajh nahi aaya. Aap phir se date bata sakte hain please?",
    "ra_filler_1": "Haan...", "ra_filler_2": "Ji haan...", "ra_filler_3": "Bilkul...",
    "ra_filler_4": "Achha...", "ra_filler_5": "Samajh gayi...", "ra_filler_6": "Theek hai...",
}

REACT_B_SCRIPT = {
    "rb_greet_main": "Pichhle kuch dino mein bahut saare customers ne apna purana furniture exchange karke naya furniture liya hai. Isliye maine socha aapko bhi call kar doon. Agar aap bhi ghar ka furniture upgrade karna chahte hain toh yeh offer kaafi useful ho sakta hai. Sunna chahenge?",
    "rb_greet_who": "Jee, main Priya bol rahi hoon Krishna Furniture ki taraf se. Aap hamare customer reh chuke hain isliye maine personally phone kiya. Soniya ji jaisi bahut families is mahine ghar badal rahi hain — aapke liye bhi yahi offer leke aayi hoon.",
    "rb_greet_repeat": "Haan ji — hum purane customers ko ek special offer de rahe hain. Purana furniture achhe rate mein khareed lenge aur naye par heavy discount denge. Aapko offer batau?",
    "rb_greet_privacy": "Jee bilkul — aapka number hamare purane customer records mein hai. Koi third party nahi. Aap hamare valued customer hain isliye personally call ki.",
    "rb_greet_hostile": "Maafi chahti hoon disturb karne ke liye. WhatsApp par details bhej deti hoon — dekhna na dekhna aap par hai. Aapka din achha rahe!",
    "rb_offer_main": "Abhi Krishna Furniture mein naye furniture par 25% discount chal raha hai. Aur purana furniture exchange karne par uski value ka bhi extra benefit milta hai. Is wajah se kaafi log expected se kam budget mein naya furniture le pa rahe hain. Ek aur baat bataun?",
    "rb_offer_explain": "Bilkul simple hai — aap showroom aao, hum aapke purane furniture ki value calculate karenge aapke saamne. Us value par 25% aur, plus upar se 25% — total saving 43 se 50%. Koi hidden condition nahi hai.",
    "rb_offer_trust": "Samajh sakti hoon — aajkal bahut calls aati hain. Aap showroom mein aa kar personally verify kar sakte hain — koi commitment nahi. Free mein value estimate ho jaati hai.",
    "rb_offer_urgency": "Is mahine bahut families aa rahi hain — pieces limited hain. Jo pehle aaya usne le liya. Aap der mat karo.",
    "rb_obj_not_interested": "Koi baat nahi — ek baar WhatsApp par photos dekh lena. Offer is mahine tak valid hai — decision aap ka hai.",
    "rb_obj_busy": "Bilkul, disturb nahi karti. Details WhatsApp par bhej deti hoon — jab time mile tab dekh lena. Offer is mahine tak valid hai.",
    "rb_obj_expensive": "Isliye toh exchange offer hai — new price par nahi, exchange ke saath. Exact amount WhatsApp par dekh sakte ho.",
    "rb_obj_online": "Online mein delivery, installation, after-sales sab alag hote hain. Yahan factory price hai plus exchange value — total comparison WhatsApp par hai.",
    "rb_obj_think": "Zaroor socho — but offer is mahine tak hi hai. WhatsApp details reh jaaye — jab decide karo tab kaam aayegi.",
    "rb_obj_recovery": "Jo families yeh offer le ke gayi hain wo bahut khush hain. Aap bhi ek baar showroom aao — free mein value estimate ho jaati hai. Koi commitment nahi.",
    "rb_hook_cta": "Aap bhi hamare purane customer hain, isliye yeh offer maine personally share kiya. Main WhatsApp par furniture ke photos, prices aur exchange process bhej deti hoon. Ek baar dekh lijiye, decision baad mein bhi le sakte hain.",
    "rb_wa_cta": "Main abhi WhatsApp par photos, prices, exchange process sab bhej rahi hoon. Ek baar dekh lena — decision baad mein karna.",
    "rb_close": "Bilkul sahi decision hai. WhatsApp dekho, ek baar showroom aao — purana furniture hum sambhal lenge, aap bas naya chunna. Bahut shukriya!",
    "rb_close_conviction": "Bahut sahi decision hai. Showroom mein aao, apne saamne value calculate karwao, aur wohi din naya furniture le jaao. Purana hum le lenge. Bahut shukriya!",
    "rb_dnc": "Maafi chahti hoon! Aapka number DNC list mein add kar diya jaayega — ab koi call nahi aayegi. Bahut bahut shukriya.",
    "rb_q_location": "Hamare showrooms Sector 14 Gurgaon, Delhi, aur Noida mein hain — Monday se Sunday, subah 10 baje se raat 8 baje tak khule rehte hain.",
    "rb_q_name": "Mera naam Priya hai — main Krishna Furniture ki taraf se baat kar rahi hoon.",
    "rb_q_valuation": "Bahut simple hai — hamari team aapke ghar aakar purana furniture dekh kar uski value batayegi, wahi se pickup bhi ho jaayega. Aapke saamne hi sab hoga.",
    "rb_appointment_ask": "Main aapke liye free valuation visit book kar deti hoon. Hamari team aa kar furniture dekh legi, value bata degi, uske baad hi aap decide kariyega. Kaunsi date convenient rahegi?",
    "rb_appointment_confirmed": "Bahut badiya ji. Main appointment confirm kar deti hoon. Hamari team time par pahunch jayegi. Jaldi milte hain!",
    "rb_appointment_reask": "Maaf kijiye, samajh nahi aaya. Aap phir se date bata sakte hain please?",
    "rb_filler_1": "Haan...", "rb_filler_2": "Ji haan...", "rb_filler_3": "Bilkul...",
    "rb_filler_4": "Achha...", "rb_filler_5": "Samajh gayi...", "rb_filler_6": "Theek hai...",
}

REACT_C_SCRIPT = {
    "rc_greet_main": "Ek chhota sa sawal poochun? Agar aapko naya furniture mil jaaye aur purana bhi achhi value mein chala jaaye, woh bhi kam kharche mein... toh kya aap uske baare mein sunna chahenge?",
    "rc_greet_who": "Jee, main Priya bol rahi hoon Krishna Furniture ki taraf se. Aap hamare customer reh chuke hain isliye maine personally phone kiya. Ek sawaal poochha tha — agar naya furniture aadhe daam mein mile toh sunenge?",
    "rc_greet_repeat": "Haan ji — main pooch rahi thi, agar aapko naya furniture mile aur purana bhi achhe rate mein chala jaaye — aadhe daam mein — toh aap sunna chahenge?",
    "rc_greet_privacy": "Jee bilkul — aapka number hamare purane customer records mein hai. Koi third party nahi. Aap hamare valued customer hain isliye personally call ki.",
    "rc_greet_hostile": "Maafi chahti hoon disturb karne ke liye. WhatsApp par details bhej deti hoon — dekhna na dekhna aap par hai. Aapka din achha rahe!",
    "rc_offer_main": "Toh bas wahi offer chal raha hai Krishna Furniture mein. Naye furniture par 25% discount hai aur purana furniture exchange karne par uski value ka bhi alag benefit milta hai. Ek aur baat bataun?",
    "rc_offer_explain": "Bilkul simple hai — aap showroom aao, hum aapke purane furniture ki value calculate karenge aapke saamne. Us value par 25% aur, plus upar se 25% — total saving 43 se 50%. Free mein value estimate ho jaati hai — koi commitment nahi.",
    "rc_offer_trust": "Samajh sakti hoon — aajkal bahut calls aati hain. Aap showroom mein aa kar personally verify kar sakte hain — koi commitment nahi. Free mein furniture ki value estimate ho jaati hai. Sirf ek baar aao toh sahi.",
    "rc_offer_urgency": "Yeh offer sirf apne purane customers ke liye hai — aur is mahine tak hi valid hai. Jo pehle aaya usne le liya. Aap der mat karo.",
    "rc_obj_not_interested": "Koi baat nahi — main force nahi kar rahi. Bas ek baar WhatsApp par photos dekh lena. Offer is mahine tak valid hai — decision aap ka hai.",
    "rc_obj_busy": "Bilkul, disturb nahi karti. Details WhatsApp par bhej deti hoon — apni fursad mein dekh lena.",
    "rc_obj_expensive": "Isliye toh yeh exchange offer hai — new price par nahi, exchange ke saath. Exact amount WhatsApp par dekh sakte ho. Free mein estimate bhi ho jaati hai showroom mein.",
    "rc_obj_online": "Online mein delivery, installation, after-sales sab alag hote hain. Hamare paas factory price hai plus exchange value — total comparison WhatsApp par hai.",
    "rc_obj_think": "Zaroor socho — main force nahi kar rahi. But offer is mahine tak hi hai. WhatsApp details reh jaaye — jab decide karo tab kaam aayegi.",
    "rc_obj_recovery": "Dekho, maine aapko force nahi karna. Bas ek baar WhatsApp dekho, showroom aao — free mein furniture ki value estimate ho jaati hai. Koi commitment nahi. Aao toh sahi.",
    "rc_hook_cta": "Yeh offer hum specially apne existing customers ke saath share kar rahe hain. Isliye maine aapko personally call kiya. Main WhatsApp par photos aur poori details bhej deti hoon. Ek baar dekh lijiye, koi commitment bilkul nahi hai.",
    "rc_wa_cta": "Main abhi WhatsApp par photos, prices, exchange process sab bhej rahi hoon. Ek baar dekh lena — decision baad mein karna. Koi commitment nahi.",
    "rc_close": "Bilkul sahi decision hai. WhatsApp dekho, ek baar showroom aao — free mein value estimate ho jaayegi. Purana furniture hum sambhal lenge, aap bas naya chunna. Bahut shukriya!",
    "rc_dnc": "Maafi chahti hoon! Aapka number DNC list mein add kar diya jaayega — ab koi call nahi aayegi. Bahut bahut shukriya.",
    "rc_q_location": "Hamare showrooms Sector 14 Gurgaon, Delhi, aur Noida mein hain — Monday se Sunday, subah 10 baje se raat 8 baje tak khule rehte hain.",
    "rc_q_name": "Mera naam Priya hai — main Krishna Furniture ki taraf se baat kar rahi hoon.",
    "rc_q_valuation": "Bahut simple hai — hamari team aapke ghar aakar purana furniture dekh kar uski value batayegi, wahi se pickup bhi ho jaayega. Aapke saamne hi sab hoga.",
    "rc_appointment_ask": "Main aapke liye free valuation visit book kar deti hoon. Hamari team aa kar furniture dekh legi, value bata degi, uske baad hi aap decide kariyega. Kaunsi date convenient rahegi?",
    "rc_appointment_confirmed": "Bahut badiya ji. Main appointment confirm kar deti hoon. Hamari team time par pahunch jayegi. Jaldi milte hain!",
    "rc_appointment_reask": "Maaf kijiye, samajh nahi aaya. Aap phir se date bata sakte hain please?",
    "rc_filler_1": "Haan...", "rc_filler_2": "Ji haan...", "rc_filler_3": "Bilkul...",
    "rc_filler_4": "Achha...", "rc_filler_5": "Samajh gayi...", "rc_filler_6": "Theek hai...",
}

ALL_SCRIPTS = {
    "react_a": REACT_A_SCRIPT,
    "react_b": REACT_B_SCRIPT,
    "react_c": REACT_C_SCRIPT,
}

def get_script(campaign: str) -> dict:
    return ALL_SCRIPTS.get(campaign, REACT_A_SCRIPT)

def get_prefix(campaign: str) -> str:
    return {"react_a": "ra", "react_b": "rb", "react_c": "rc"}.get(campaign, "ra")


# ─────────────────────────────────────────────────────────────────────────────
# SHARED — Q&A/appointment keys migrated to per-plan dicts (ra_/rb_/rc_).
# Kept as empty dict so utility scripts that import SHARED_SCRIPT don't error.
# ─────────────────────────────────────────────────────────────────────────────
SHARED_SCRIPT = {}

SHARED_INTENTS = {
    "ask_location": ["kahan hai", "showroom kahan", "location kya", "address batao",
                     "kaha hai showroom", "kahan par hai", "kaunsi jagah",
                     "कहां है", "कहाँ है", "शोरूम कहां", "लोकेशन क्या", "एड्रेस बताओ",
                     "कहां पर है", "कहाँ पर है", "स्टोर कहां", "स्टोर कहाँ", "कौनसी जगह",
                     "दुकान कहां", "shop kahan", "store kahan", "showroom kaha"],
    "ask_name": ["tumhara naam", "aapka naam", "naam kya hai", "kaun bol rahe ho",
                "तुम्हारा नाम", "आपका नाम", "नाम क्या है", "कौन बोल रहे हो", "कौन बोल रही हो"],
    "ask_timings": ["time kya", "kab khulta", "timing kya hai", "kitne baje khulta",
                    "टाइम क्या", "कब खुलता", "टाइमिंग क्या है", "कितने बजे खुलता"],
    "ask_valuation": ["valuation kaise", "purana furniture kaise", "kaise pickup",
                      "value kaise milegi", "kaise calculate", "kaise lenge purana",
                      "वैल्यूएशन कैसे", "पुराना फर्नीचर कैसे", "कैसे पिकअप", "वैल्यू कैसे मिलेगी",
                      "कैसे कैलकुलेट", "कैसे लेंगे पुराना"],
    "ask_delivery": ["delivery kab", "kab milega", "kitne din mein", "delivery kaise",
                     "डिलीवरी कब", "कब मिलेगा", "कितने दिन में", "डिलीवरी कैसे"],
    "appointment_confirm": ["kal", "parso", "monday", "tuesday", "wednesday", "thursday",
                            "friday", "saturday", "sunday", "subah", "shaam", "raat",
                            "baje", "tareek", "date", "theek hai aa jaunga", "main aaunga",
                            "book kardo", "haan book karo", "confirm hai", "ji confirm",
                            "कल", "परसों", "सोमवार", "मंगलवार", "बुधवार", "गुरुवार",
                            "शुक्रवार", "शनिवार", "रविवार", "सुबह", "शाम", "रात", "बजे",
                            "तारीख", "ठीक है आ जाऊंगा", "मैं आऊंगा", "बुक कर दो",
                            "हां बुक करो", "कन्फर्म है", "जी कन्फर्म",
                            "सैटरडे", "सैंडे", "संडे", "मंडे", "ट्यूज़डे", "ट्यूजडे",
                            "वेडनेसडे", "थर्सडे", "फ्राइडे", "वीकेंड", "weekend",
                            "बैटर डे", "बैटरडे", "सैटर डे",
                            "सन डे", "मन डे", "ट्यूज डे", "वेड नेस डे", "थर्स डे", "फ्राई डे",
                            "जनवरी", "फरवरी", "मार्च", "अप्रैल", "मई", "जून",
                            "जुलाई", "अगस्त", "सितंबर", "अक्टूबर", "नवंबर", "दिसंबर",
                            "january", "february", "march", "april", "june", "july",
                            "august", "september", "october", "november", "december",
                            "agle hafte", "agle mahine", "अगले हफ्ते", "अगले महीने",
                            "is hafte", "इस हफ्ते"],
}

REACT_ABC_INTENTS = {
    "positive": ["haan", "han", "haa", "theek hai", "batao", "bolo", "sun raha hoon",
                 "okay", "ok", "sure", "bilkul", "achha", "bataiye", "sunenge", "ji",
                 "जी", "हाँ", "हां", "ठीक है", "बताओ", "बोलो", "अच्छा", "बिल्कुल"],
    "confusion_who": ["kaun", "kahan se", "kon ho", "pahchaan nahi", "kaun sa number",
                      "kaise mila", "number kahan se", "कौन", "कहाँ से", "पहचान नहीं"],
    "repeat": ["kya", "kya bola", "phir se bolo", "samjha nahi", "dobara bolo",
               "suna nahi", "क्या", "क्या बोला", "फिर से", "समझा नहीं"],
    "privacy_concern": ["number kaise mila", "data kahan se", "mera number kyun hai", "spam", "privacy"],
    "offer_clarify": ["kya offer", "kaise hoga", "explain karo", "samjhao",
                      "exchange kaise", "purana furniture", "kya matlab",
                      "detail batao", "aur batao", "एक्सचेंज कैसे", "exchange kaisa"],
    "trust_issue": ["fake hai", "jhooth", "fraud", "scam", "sach mein",
                    "pakka", "sach hai kya", "vishwas nahi"],
    "buying_signal": ["kitna time hai", "kab tak hai", "interested hoon",
                      "showroom kab", "aana chahta", "visit karna", "kab aaye"],
    "wa_ok": ["bhejo", "send karo", "bhej do", "kar do", "theek hai bhej do",
              "ok send", "haan bhejo", "ठीक है", "okay", "haan", "हाँ",
              "bilkul", "sure", "done", "ji", "जी", "achha", "अच्छा",
              "ok ok", "oke", "okey", "bhej do", "ओके", "ओके ओके",
              "de do", "kar lo", "chal", "haa", "ha"],
    "wa_no_whatsapp": ["whatsapp nahi hai", "use nahi karta", "no whatsapp"],
    "wa_diff_number": ["alag number", "doosra number", "different number"],
    "wa_prefers": ["whatsapp pe hi", "call nahi", "message karo"],
    "busy": ["busy hoon", "abhi nahi", "kaam mein hoon", "baad mein", "driving",
             "meeting mein", "abhi nahi kar sakta"],
    "not_interested": ["interested nahi", "nahi chahiye", "rehne do",
                       "hata do mera number", "band karo", "mat bhejo"],
    "expensive": ["mahenga hai", "bahut zyada", "budget nahi", "afford nahi", "costly"],
    "online_cheaper": ["online sasta", "amazon pe", "flipkart pe", "online better"],
    "sochna_hai": ["sochna hai", "soch ke batata hoon", "wife se puchna",
                   "family se puchna", "decide nahi kiya"],
    "escalate": ["manager se baat", "senior se milao", "complaint karna"],
    "dnc": ["dobara call mat karna", "number delete karo", "DNC", "harassment",
            "complaint karunga", "call mat karo kabhi", "band karo yeh call"],
    "personal_question": ["tumhara naam", "kaun ho tum", "real hai ya bot",
                          "robot ho", "AI ho", "human ho"],
}
